-- Add avatar_url to Users
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS avatar_url text;

-- Notifications table
CREATE TABLE IF NOT EXISTS "Notifications" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  recipient_id uuid NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  actor_id uuid NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('like', 'comment', 'follow')),
  post_id bigint,
  read boolean DEFAULT false NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON "Notifications"(recipient_id, created_at DESC);
