-- Add avatar_url to Users
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS avatar_url text;

-- Notifications table
CREATE TABLE IF NOT EXISTS "Notifications" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  recipient_id uuid NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  actor_id uuid NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('like', 'comment', 'follow')),
  post_id bigint,
  read boolean DEFAULT false NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON "Notifications"(recipient_id, created_at DESC);

-- Hashtags table
CREATE TABLE IF NOT EXISTS "Hashtags" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag text NOT NULL UNIQUE,
  post_count int DEFAULT 0,
  last_used_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_hashtags_tag ON "Hashtags"(tag);
CREATE INDEX IF NOT EXISTS idx_hashtags_post_count ON "Hashtags"(post_count DESC);

-- PostHashtags junction table (no FK on post_id — Posts may lack explicit PK constraint)
CREATE TABLE IF NOT EXISTS "PostHashtags" (
  post_id bigint NOT NULL,
  hashtag_id bigint NOT NULL REFERENCES "Hashtags"(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, hashtag_id)
);

CREATE INDEX IF NOT EXISTS idx_posthashtags_hashtag ON "PostHashtags"(hashtag_id);
CREATE INDEX IF NOT EXISTS idx_posthashtags_post ON "PostHashtags"(post_id);

-- Mentions table
CREATE TABLE IF NOT EXISTS "Mentions" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  mentioned_user_id uuid NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  actor_id uuid NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
  post_id bigint,
  comment_id bigint,
  CHECK (post_id IS NOT NULL OR comment_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_mentions_user ON "Mentions"(mentioned_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mentions_post ON "Mentions"(post_id);
CREATE INDEX IF NOT EXISTS idx_mentions_comment ON "Mentions"(comment_id);

-- Extend notification type check to include 'mention'
ALTER TABLE "Notifications" DROP CONSTRAINT IF EXISTS "Notifications_type_check";
ALTER TABLE "Notifications" ADD CONSTRAINT "Notifications_type_check"
  CHECK (type IN ('like', 'comment', 'follow', 'mention'));

-- RPC to increment post_count for hashtags
CREATE OR REPLACE FUNCTION increment_hashtag_post_count(tag_names text[])
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE "Hashtags"
  SET post_count = COALESCE(post_count, 0) + 1, last_used_at = now()
  WHERE tag = ANY(tag_names);
END;
$$;

-- RPC to decrement post_count for hashtags (used when post is deleted)
CREATE OR REPLACE FUNCTION decrement_hashtag_post_count(tag_names text[])
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE "Hashtags"
  SET post_count = GREATEST(COALESCE(post_count, 0) - 1, 0)
  WHERE tag = ANY(tag_names);
END;
$$;
